apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zipkin
  namespace: namespace2
spec:
  destination:
    namespace: namespace2
    server: https://kubernetes.default.svc
  project: project1
  source:
    helm:
      valueFiles:
        - values.dev-migra.yaml
    path: helm-chart
    repoURL: https://<app_repo_url>/zipkin.git
    targetRevision: HEAD